
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "APP", targetNamespace = "http://Server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface APP {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "send_many_email")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "send_many_email", targetNamespace = "http://Server/", className = "server.SendManyEmail")
    @ResponseWrapper(localName = "send_many_emailResponse", targetNamespace = "http://Server/", className = "server.SendManyEmailResponse")
    @Action(input = "http://Server/APP/send_many_emailRequest", output = "http://Server/APP/send_many_emailResponse")
    public String sendManyEmail(
            @WebParam(name = "arg0", targetNamespace = "")
                    List<String> arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testWebService", targetNamespace = "http://Server/", className = "server.TestWebService")
    @ResponseWrapper(localName = "testWebServiceResponse", targetNamespace = "http://Server/", className = "server.TestWebServiceResponse")
    @Action(input = "http://Server/APP/testWebServiceRequest", output = "http://Server/APP/testWebServiceResponse")
    public String testWebService(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "send_email")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "send_email", targetNamespace = "http://Server/", className = "server.SendEmail")
    @ResponseWrapper(localName = "send_emailResponse", targetNamespace = "http://Server/", className = "server.SendEmailResponse")
    @Action(input = "http://Server/APP/send_emailRequest", output = "http://Server/APP/send_emailResponse")
    public String sendEmail(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "send_mass_texting")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "send_mass_texting", targetNamespace = "http://Server/", className = "server.SendMassTexting")
    @ResponseWrapper(localName = "send_mass_textingResponse", targetNamespace = "http://Server/", className = "server.SendMassTextingResponse")
    @Action(input = "http://Server/APP/send_mass_textingRequest", output = "http://Server/APP/send_mass_textingResponse")
    public String sendMassTexting(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateEmailAddress", targetNamespace = "http://Server/", className = "server.ValidateEmailAddress")
    @ResponseWrapper(localName = "validateEmailAddressResponse", targetNamespace = "http://Server/", className = "server.ValidateEmailAddressResponse")
    @Action(input = "http://Server/APP/validateEmailAddressRequest", output = "http://Server/APP/validateEmailAddressResponse")
    public String validateEmailAddress(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
